services:
  app:
    build:
      context: .
    ports:
    - "8888:3001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npx nodemon --watch src --exec ts-node src/app.ts"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure